twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # the value is the service's id
        # periods: '@App\Generator\PeriodsGenerator'
        types: '@App\Service\TypeGenerator'

when@test:
    twig:
        strict_variables: true
